version: '3.8'
services:
  postgis:
    container_name: postgis
    image: gis_test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=main
    ports:
      - '5432:5432'
  